methods_tab <- tabPanel("Methods",
                        fluidPage(
                          tags$div(
                            id = "methods-content",
                            
                            tags$h2("Methodology", style = "color: #001f87;"),
                            
                            tags$p("In our analysis, we performed a geographic difference-in-differences model to estimate the effect of USSFs on land values with treatment defined at the county level. A difference-in-differences model is a form of linear regression that estimates a possible causal effect of a treatment or intervention by comparing the change in outcomes over time for a treated group to the change over the same period  for an untreated control group, and therefore accounts for pre-existing differences as well as more common time trends. As previously stated, we included multiple key variables (Fig 1) in our linear regression model to get an indication of how each of them affects land prices at the county level. To better interpret our results we constructed our difference-in-differences variable (DiD_ct in Fig 2) as an indicator variable that takes a value of 1 for observation in counties that already had a USSF by the year of the land parcel transaction, and 0 otherwise (i.e., for transactions occurring before USSF development, and for all transactions occurring in control counties that never have a USSF during our study period)."),
                            
                            tags$p("We collected data pertaining to land price per acre (our dependent variable), which allowed us to evaluate the total dollar value of land sold per acre in Virginia. From this we were able to better analyze how land prices have changed over time in each county, and whether or not this is linked with the development of a USSF in that county. Our dependent variable in our model was LandPrice_per_acre (Fig 1), is the phenomena we hope to observe change over time due to the development of USSF’s. Next, we collected multiple independent variables starting with crop yield data specifically of corn and soybeans because they are the 2 most profitable crops in Virginia. Additionally crop yields act as an important indicator of soil quality, and high crop yields relate to higher soil quality (D’Hose, Cougnon, Vliegher, Vandacasteele, Viane, Cornelis, Bockstaele, Reheul, 2014). The higher the soil quality, the more valuable the farmland. Another variable in our model is population, which acts as a control for migration, and serves to help explain the viability of land per county based on how many people live there. The average age of houses, which allowed us to understand the mean age of houses per county, also helped explain the age of houses and whether or not the county was a place of higher development and therefore higher land value.  The inclusion of total housing units as well as occupied housing units helps us understand the amount of house building in that county, and if the land is more sought after for building and development and is therefore more valuable. Observing vacant housing units per county acted as an important factor which can drive land prices like occupied and total housing units, and it shows how sought after an area is to live, and demand in some cases can be correlated with higher land values."),
                            
                            tags$p("Finally, we included county and year level fixed effects. County level fixed effects allowed us to understand all of the variables affecting different counties that do no vary over time which could not be included in our model. Year level fixed effects allowed us to understand some of the underlying economic fluctuations which affect every part of the state such as changing inflation, policy, GDP, etc., that vary over time but not space. Due to time invariance, SolarFacility_c and TransactionYear_t are absorbed by these fixed effects and cannot be estimated separately. The setup of our DID_ct variable (Fig 1) is the primary way to capture the effect of interest in out two-way fixed effects setup. A crucial step towards correctly interpreting our model was to use clustered standard errors. Since some land sales are connected, this means that our linear model could create results that are more significant than what is realistic. Our solution to this problem was to include an adjusted coeftest with clustered standard errors, which will allow us to have more accurate p-values and a more robust measure of the statistical significance of our results.")
                          )
                        )
)
